name: main
on: push

jobs:
  build:
    name: Build-n-stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install dependency libnet
        run: sudo apt-get install -y libnet1-dev

      - name: install dependency libpcap
        run: sudo apt-get install -y libpcap-dev

      - name: build
        run: make
  
